linters:
  enable:
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    #- gocritic
    - godot
    - godox
    #- goerr113
    - gofmt
    - gofumpt
    #- goheader
    - goimports
    - gomoddirectives
    - gosec
    - gosmopolitan
    - inamedparam
    - interfacebloat
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - sloglint
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - varnamelen
    - wastedassign
  disable:
    - unused
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  revive:
    severity: warning
    enable-all-rules: true
    rules:
      - name: cyclomatic
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: function-length
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: exported
        severity: error
      - name: unused-parameter
        severity: error
      - name: add-constant
        arguments:
          - maxLitCount: "3"
            allowStrs: "\"\",\"No\""
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."

