ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0
enableAllRules = true

[rule.cyclomatic]
    disabled = true
[rule.cognitive-complexity]
    disabled = true
[rule.function-length]
    disabled = true
[rule.line-length-limit]
    disabled = true

[rule.add-constant]
    arguments = [{maxLitCount = "3",allowStrs ="\"\"",allowInts="0,1,2",allowFloats="0.0,0.,1.0,1.,2.0,2."}]

[rule.exported]
    severity = "error"
[rule.unused-parameter]
    severity = "error"


